version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: aloy_postgres_dev
    environment:
      POSTGRES_DB: aloy_dev
      POSTGRES_USER: aloy
      POSTGRES_PASSWORD: aloy123
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - aloy_dev_network

  # Message Broker RabbitMQ
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: aloy_rabbitmq_dev
    environment:
      RABBITMQ_DEFAULT_USER: aloy
      RABBITMQ_DEFAULT_PASS: aloy123
    volumes:
      - rabbitmq_dev_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - aloy_dev_network

  # Redis para cache
  redis:
    image: redis:7-alpine
    container_name: aloy_redis_dev
    command: redis-server --appendonly yes --requirepass aloy123
    volumes:
      - redis_dev_data:/data
    ports:
      - "6379:6379"
    networks:
      - aloy_dev_network

volumes:
  postgres_dev_data:
  rabbitmq_dev_data:
  redis_dev_data:

networks:
  aloy_dev_network:
    driver: bridge
