version: '3.8'

services:
  # Banco de dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: aloy_postgres_dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}_dev
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "${POSTGRES_PORT}:5432"
    networks:
      - aloy_dev_network

  # Message Broker RabbitMQ
  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    container_name: aloy_rabbitmq_dev
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_dev_data:/var/lib/rabbitmq
    ports:
      - "${RABBITMQ_AMQP_PORT}:5672"
      - "${RABBITMQ_UI_PORT}:15672"
    networks:
      - aloy_dev_network

  # Redis para cache
  redis:
    image: redis:7-alpine
    container_name: aloy_redis_dev
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_dev_data:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - aloy_dev_network

volumes:
  postgres_dev_data:
  rabbitmq_dev_data:
  redis_dev_data:

networks:
  aloy_dev_network:
    driver: bridge
